site_name: Jim Raynor Blog

theme:
  name: leap-day   # tu tema elegido
  palette:
    scheme: slate  # modo oscuro (si tu tema lo soporta)
  custom_dir: theme   # carpeta donde pondremos CSS personalizado

plugins:
  - search
  - awesome-pages
  - section-index
