site_name: Jim Raynor's site
site_url: https://jim88.pp.ua
#repo_url: https://github.com/jimraynor88/jimraynor88.github.io
#repo_name: GitHub
edit_uri: ""
repo_url: https://ko-fi.com/invito
repo_name: Invítame al Ko-Fi

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
  icon:
    repo: fontawesome/solid/mug-hot
  
  highlightjs: true

extra_css:
  - assets/stylesheets/kofi.css

plugins:
  - search
  - awesome-pages
  - section-index
  - rss
  - bettertags

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jimraynor88
      name: GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/jimraynor1488
      name: X
    - icon: fontawesome/solid/envelope
      link: mailto:jimraynor@duck.com
      name: Email
    - icon: fontawesome/brands/telegram
      link: https://t.me/jimraynorbot
      name: Telegram
    - icon: fontawesome/solid/mug-hot
      link: https://ko-fi.com/invito
      name: Invítame al Ko-Fi

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.superfences
  - tables
  - attr_list

extra_javascript:
  - https://storage.ko-fi.com/cdn/widget/Widget_2.js
  - js/kofi_button.js
