name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Instalar MkDocs y todos los plugins juntos
      - run: pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-section-index mkdocs-rss-plugin mkdocs-leap-day
      
      # Construir sitio
      - run: mkdocs build

      # Publicar en GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
