name: Deploy MkDocs

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

        
      - name: Generate blog index pages
        run: python generate_blog_index.py

      # Aquí es donde se ejecuta el nuevo script
      - name: Generate products JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pasa el token al script
        run: python scripts/fetch_products.py

      # NUEVO PASO: Generar la tienda
      - name: Generate shop data
        run: python scripts/generar_tienda.py

      - name: Build site
        run: mkdocs build --strict
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         
      - name: Add prev/next links
        run: python add_prev_next.py site   # pasa el directorio de salida
               
      - name: Add CNAME
        run: echo "jim88.pp.ua" > ./site/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
